quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=051175Rob
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/Corsi

quarkus.hibernate-orm.database.generation=update

# Abilita CORS
quarkus.http.cors=true

# Permetti richieste dal frontend React
quarkus.http.cors.origins=http://localhost:5173

# Metodi HTTP permessi
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

# Headers permessi
quarkus.http.cors.headers=Content-Type,Authorization

# Se vuoi supportare cookie/sessioni
quarkus.http.cors.access-control-allow-credentials=true

# Security
quarkus.http.auth.form.enabled=false
quarkus.http.auth.permission.all.paths=authenticated
quarkus.http.auth.permission.all.policy=permit